-- SQL migration to create post_comments table for comments attached to posts
-- Run this in your Supabase SQL editor or psql against the project's DB

CREATE TABLE IF NOT EXISTS public.post_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post bigint NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
  "user" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  comment text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- optional indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_post_comments_post ON public.post_comments(post);
CREATE INDEX IF NOT EXISTS idx_post_comments_user ON public.post_comments("user");

-- Grant minimal privileges (adjust role names as needed)
GRANT SELECT, INSERT ON public.post_comments TO authenticated;
